version: '3.4'

services:
  pocredis:
    image: ${DOCKER_REGISTRY-}pocredis
    build:
      context: .
      dockerfile: POCRedis/Dockerfile
    depends_on:
      - redis

  redis: 
    image: redis
    ports: 
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes